mode: train
project: "Trinity-RFT-example"
name: "sft_mot"
checkpoint_root_dir: /PATH/TO/CHECKPOINT/
algorithm:
  algorithm_type: sft
model:
  model_path: /PATH/TO/MODEL/
  max_response_tokens: 10240
  max_model_len: 10752
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  train_batch_size: 64
  trainer_input:
    experience_buffer:
      name: MoT
      storage_type: file
      path: open-r1/Mixture-of-Thoughts
      subset_name: math
      format:
        prompt_type: messages
        messages_key: messages
synchronizer:
  sync_method: 'checkpoint'
  sync_interval: 10
trainer:
  save_interval: 10
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: true
      actor:
        use_dynamic_bsz: true
        ppo_max_token_len_per_gpu: 22000
        ulysses_sequence_parallel_size: 1
        optim:
          lr: 1e-5
      ref:
        log_prob_use_dynamic_bsz: ${trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}
        log_prob_max_token_len_per_gpu: ${trainer.trainer_config.actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
        ulysses_sequence_parallel_size: ${trainer.trainer_config.actor_rollout_ref.actor.ulysses_sequence_parallel_size}
