mode: train
project: "Trinity-RFT-example"
name: "sft_mot"
checkpoint_root_dir: /PATH/TO/CHECKPOINT/
algorithm:
  algorithm_type: sft
model:
  model_path: /PATH/TO/MODEL/
  max_prompt_tokens: 512
  max_response_tokens: 10240
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 32
  max_retry_times: 3
  max_retry_interval: 1
  trainer_input:
    experience_buffer:
      name: MoT
      storage_type: file
      path: open-r1/Mixture-of-Thoughts
      subset_name: math
      format:
        prompt_type: messages
        messages_key: messages
synchronizer:
  sync_method: 'checkpoint'
  sync_interval: 10
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/sft_mot/train_sft.yaml'
  save_interval: 10
