project: "Trinity-RFT-RAFT-alfworld"
name: "qwen2.5-7B-RAFT-alfworld"
mode: both
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: raft
  repeat_times: 1
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-7B-Instruct}
  max_response_tokens: 4096
  max_model_len: 20480
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 30
  batch_size: 80
  explorer_input:
    taskset:
      name: alfworld-train
      storage_type: file
      path: ${oc.env:TRINITY_TASKSET_PATH}
      split: 'train'
      format:
        prompt_key: 'game_file'
        response_key: 'task_desc'
      rollout_args:
        temperature: 0.85
        top_k: 25
        top_p: 0.95
    eval_tasksets:
      - name: alfworld-eval
        storage_type: file
        path: ${oc.env:TRINITY_TASKSET_PATH}
        split: 'test'
        format:
          prompt_key: 'game_file'
          response_key: 'task_desc'
        rollout_args:
          temperature: 0.85
          top_k: 25
          top_p: 0.95
    default_workflow_type: 'RAFT_alfworld_workflow'
  trainer_input:
    experience_buffer:
      name: RAFT_buffer
      storage_type: queue
      path: 'sqlite:///RAFT_alfworld.db'
explorer:
  eval_interval: 30
  runner_per_model: 8
  max_timeout: 3000  # Increased timeout for alfworld environment interactions
  max_retry_times: 2
  rollout_model:
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: true
    enforce_eager: false
    dtype: bfloat16
    gpu_memory_utilization: 0.86
    seed: 42
synchronizer:
  sync_style: dynamic_by_explorer
  sync_method: 'nccl'
  sync_interval: 4
  sync_timeout: 1200
trainer:
  save_interval: 100000
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: true
      actor:
        use_dynamic_bsz: true
        ppo_max_token_len_per_gpu: 20000  # Adjusted for alfworld longer sequences
        ulysses_sequence_parallel_size: 1
        optim:
          lr: 1e-6
      ref:
        log_prob_use_dynamic_bsz: ${trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}
        log_prob_max_token_len_per_gpu: ${trainer.trainer_config.actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
        ulysses_sequence_parallel_size: ${trainer.trainer_config.actor_rollout_ref.actor.ulysses_sequence_parallel_size}
    trainer:
      resume_mode: disable
      remove_previous_ckpt_in_save: true
monitor:
  monitor_type: wandb
