project: "dpo_example"
name: "trinity_dpo"
mode: train

# using task pipeline to decide the chosen and rejected from human preference
data_processor:
  # task pipeline related
  task_pipeline:
    num_process: 1
    operators:
      - name: "human_preference_annotation_mapper"
        args:
          # general annotation project settings
          project_name_prefix: "Human_Preference_Annotation_Demo"
          wait_for_annotations: true  # Whether to wait for annotations to complete
          timeout: 3600  # Maximum time to wait for annotations in seconds (1 hour)
          poll_interval: 10  # Time between annotation status checks in seconds
          max_tasks_per_batch: 10  # Maximum number of tasks in a single batch
          notification_config:
            enabled: false

          # label studio connection settings
          api_url: "http://localhost:7070"  # Default Label Studio URL
          api_key: "YOUR_API_KEY"  # Your API key for label studuio authentication, which can be set when starting the label-studio service

          # human preference annotation settings
          prompt_key: "prompt"  # Prompt field
          answer1_key: "answer1"  # First answer option
          answer2_key: "answer2"  # Second answer option
          chosen_key: "chosen"  # Chosen field
          rejected_key: "rejected"  # Rejected field
    inputs:  # the output will be set to the explorer input automatically
      - 'examples/dpo_human_in_the_loop/demo-data.jsonl'
    target_fields: ["prompt"]
service:
  data_juicer:
    auto_start: true

algorithm:
  algorithm_type: dpo
  kl_loss_fn: k1
  kl_loss_fn_args:
    kl_coef: 0.1
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-7B-Instruct}
  max_response_tokens: 1024
  max_model_len: 1536
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 2
  train_batch_size: 64
  trainer_input:
    experience_buffer:
      name: dpo_buffer
      storage_type: file
      enable_progress_bar: True
      path: ./outputs/human_annotation_output/  # the result data after human preference annotation are stored here
      format:
        prompt_type: plaintext # plaintext/messages
        prompt_key: prompt
        chosen_key: chosen
        rejected_key: rejected
synchronizer:
  sync_method: 'checkpoint'
  sync_interval: 30
  sync_timeout: 1200
trainer:
  save_interval: 30
  total_steps: 200
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: false
      actor:
        use_dynamic_bsz: false
        ppo_micro_batch_size_per_gpu: 2
        ppo_max_token_len_per_gpu: 16384
        ulysses_sequence_parallel_size: 1
        optim:
          lr: 5e-7
          lr_warmup_steps_ratio: 0.03  # the total steps will be injected during runtime
          min_lr_ratio: 0.1   # only useful for warmup with cosine
          warmup_style: cosine  # select from constant/cosine
          betas: [0.9, 0.95]
      ref:
        log_prob_micro_batch_size_per_gpu: 2
        log_prob_use_dynamic_bsz: ${trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}
        log_prob_max_token_len_per_gpu: ${trainer.trainer_config.actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
        ulysses_sequence_parallel_size: ${trainer.trainer_config.actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size
    trainer:
      balance_batch: false
