project: Trinity-RFT-example
name: dapo
checkpoint_root_dir: /PATH/TO/CHECKPOINT/
model:
  model_path: /PATH/TO/MODEL/
algorithm:
  algorithm_type: grpo
  repeat_times: 16
  policy_loss_fn_args:
    clip_range_low: 0.2
    clip_range_high: 0.28
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 32
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: dapo-math
      storage_type: file
      path: open-r1/DAPO-Math-17k-Processed
      subset_name: all
      format:
        prompt_key: 'prompt'
        response_key: 'solution'
        system_prompt: 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.'
      rollout_args:
        temperature: 1.0
        logprobs: 0
      workflow_args:
        use_base: true
      reward_fn_args:
        enable_overlong_penalty: true
        penalty_factor: 1.0
        max_response_length: 20480
        cache_length: 4096
    eval_tasksets:
    - name: AIME2024
      storage_type: file
      path: /PATH/TO/AIME2024/
      split: 'test'
      format:
        prompt_key: 'question'
        response_key: 'answer'
        system_prompt: 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.'
      rollout_args:
        n: 32
        temperature: 1.0
        top_p: 0.7
    default_workflow_type: 'math_boxed_workflow'
    default_reward_fn_type: 'math_dapo_reward'
  trainer_input:
    experience_buffer:
      name: math_buffer
      storage_type: queue
explorer:
  eval_interval: 10
  runner_num: 32
  rollout_model:
    engine_type: vllm_async
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    max_prompt_tokens: 1024
    max_response_tokens: 20480
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 16
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/dapo_math/train_dapo.yaml'
  save_interval: 100
