# Configuration file for the REC GSM8k project.
project: "Trinity-RFT-GSM8K"
name: rec_gsm8k
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
mode: both
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-3B-Instruct}
  max_response_tokens: 1024
  max_model_len: 1280
algorithm:
  algorithm_type: rec
  policy_loss_fn_args:
    epsilon_low: 0.2
    epsilon_high: 0.2
    clip_mode: "none"
    weight: "none"
    temp: 1.0
    regularizer: "none"
    regularizer_coef: 0.0
  advantage_fn_args:
    std_normalize: false
  repeat_times: 8
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_steps: 100
  batch_size: 96
  explorer_input:
    taskset:
      name: gsm8k
      storage_type: file
      path: ${oc.env:TRINITY_TASKSET_PATH}
      split: train
      format:
        prompt_key: question
        response_key: answer
      rollout_args:
        temperature: 1.0
    eval_tasksets:
      - name: gsm8k-eval
        storage_type: file
        path: ${oc.env:TRINITY_EVAL_TASKSET_PATH}
        split: test
        format:
          prompt_key: question
          response_key: answer
    default_workflow_type: math_workflow
  trainer_input:
    experience_buffer:
      name: gsm8k_buffer
      storage_type: queue
explorer:
  eval_interval: 20
  runner_num: 64
  rollout_model:
    engine_type: vllm_async
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: nccl
  sync_interval: 20
  sync_timeout: 1200
  sync_offset: 0
trainer:
  trainer_type: verl
  save_interval: 100
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: true
      actor:
        use_dynamic_bsz: true
        ppo_max_token_len_per_gpu: 16384
        ulysses_sequence_parallel_size: 1
        optim:
          lr: 1e-6
      ref:
        log_prob_use_dynamic_bsz: ${trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}
        log_prob_max_token_len_per_gpu: ${trainer.trainer_config.actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
        ulysses_sequence_parallel_size: ${trainer.trainer_config.actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size
