from abc import ABC, abstractmethod
from typing import Dict, List, Tuple

import torch

from trinity.utils.registry import Registry

POLICY_LOSS_FN = Registry("policy_loss_fn")


class PolicyLossFn(ABC):
    """
    Policy Loss Function
    """

    @abstractmethod
    def __call__(
        self,
        logprob: torch.Tensor,
        **kwargs,
    ) -> Tuple[torch.Tensor, Dict]:
        """
        Args:
            logprob (`torch.Tensor`): The log probability generated by the policy model.
            old_logprob (`torch.Tensor`): The log probability generated by the reference model.
            action_mask (`torch.Tensor`): The action mask.
            advantages (`torch.Tensor`): The advantages.
            kwargs (`Dict`): The step-level parameters for calculating the policy loss.

        Returns:
            `torch.Tensor`: Policy loss
            `Dict`: The metrics for logging.
        """

    @classmethod
    @abstractmethod
    def default_args(cls) -> Dict:
        """
        Returns:
            `Dict`: The default init arguments for the policy loss function.
        """

    @property
    @abstractmethod
    def select_keys(self) -> List[str]:
        """
        Returns:
            `List[str]`: The keys to select from input data.
        """
