project: "Trinity-RFT-countdown"
name: "qwen2.5-1.5B-countdown"
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: ppo
  repeat_times: 5
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-1.5B-Instruct}
  max_response_tokens: 1024
  max_model_len: 1280
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 20
  batch_size: 96
  explorer_input:
    taskset:
      name: countdown
      storage_type: file
      path: 'countdown_dataset/oneshot-split'
      format:
        prompt_key: 'question'
        response_key: 'answer'
      rollout_args:
        temperature: 1.0
    default_workflow_type: 'math_workflow'
    default_reward_fn_type: 'countdown_reward'
  trainer_input:
    experience_buffer:
      name: countdown_buffer
      storage_type: queue
      path: 'sqlite:///countdown.db'
explorer:
  eval_interval: 100
  runner_per_model: 8
  rollout_model:
    engine_num: 2
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 10
  sync_timeout: 1200
trainer:
  save_interval: 100
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: true
      actor:
        strategy: megatron  # This is for backward-compatibility
        megatron:
          # parallelism settings
          tensor_model_parallel_size: 2
          pipeline_model_parallel_size: 1
          expert_model_parallel_size: 1
          # offload settings
          param_offload: false
          grad_offload: false
          optimizer_offload: false
          # whether to use mbridge to import/export parameters
          use_mbridge: false
          # Use Megatron checkpoint
          use_dist_checkpointing: false
          dist_checkpointing_path: null
          # recompute settings
          override_transformer_config:
            recompute_granularity: full
            recompute_method: uniform
            recompute_num_layers: 1
        use_dynamic_bsz: true
        ppo_max_token_len_per_gpu: 16384
        ulysses_sequence_parallel_size: 1 # sp size
        checkpoint:
          load_contents: ['model', 'hf_model', 'optimizer', 'extra']
          save_contents: ['model', 'hf_model', 'optimizer', 'extra']
        optim:
          lr: 1e-6
      ref:
        megatron:
          tensor_model_parallel_size: 2
          pipeline_model_parallel_size: 1
          expert_model_parallel_size: 1
          param_offload: false
          grad_offload: false
          optimizer_offload: false
          use_mbridge: false
          use_dist_checkpointing: false
          dist_checkpointing_path: null
          override_transformer_config:
            recompute_granularity: full
            recompute_method: uniform
            recompute_num_layers: 1
        log_prob_use_dynamic_bsz: ${trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}
        log_prob_max_token_len_per_gpu: ${trainer.trainer_config.actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
        ulysses_sequence_parallel_size: ${trainer.trainer_config.actor_rollout_ref.actor.ulysses_sequence_parallel_size}
    critic:
      strategy: megatron
      megatron:
        tensor_model_parallel_size: 2
        pipeline_model_parallel_size: 1
        expert_model_parallel_size: 1
        param_offload: false
        grad_offload: false
        optimizer_offload: false
        use_mbridge: false
        use_dist_checkpointing: false
        dist_checkpointing_path: null
        override_transformer_config:
          recompute_granularity: full
          recompute_method: uniform
          recompute_num_layers: 1
      optim:
        lr: 1e-5
      ppo_micro_batch_size_per_gpu: 8
      forward_micro_batch_size_per_gpu: ${trainer.trainer_config.critic.ppo_micro_batch_size_per_gpu}
      use_dynamic_bsz: ${trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}
      ppo_max_token_len_per_gpu: 32768 # (${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}) * 2
      forward_max_token_len_per_gpu: ${trainer.trainer_config.critic.ppo_max_token_len_per_gpu}
      ulysses_sequence_parallel_size: 1 # sp size
      grad_clip: 1.0
      cliprange_value: 0.5
    trainer:
      max_actor_ckpt_to_keep: 5
      max_critic_ckpt_to_keep: 5
