# Configuration file for the AsymRE Math project.
# REINFORCE for off-Policy Reinforcement Learning: Balancing positive and negative rewards
# https://arxiv.org/abs/2506.20520.
project: "Trinity-RFT-MATH"
name: asymre_math
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-3B-Instruct} # the path to your model
  max_response_tokens: 1024
  max_model_len: 1280
algorithm:
  algorithm_type: asymre
  policy_loss_fn_args:
    tau: 0
  advantage_fn_args:
    baseline_shift: -0.1  # Baseline shift for the AsymRE
  repeat_times: 8
cluster:
  node_num: 1
  gpu_per_node: 8

buffer:
  total_steps: 2000    # Exactly 2000 training steps as desired
  batch_size: 16       # 128 trajectories per gradient step, batch_size is the number of tasks per batch
  explorer_input:
    taskset:
      name: math
      storage_type: file
      path: ${oc.env:TRINITY_TASKSET_PATH}
      format:
        prompt_key: 'problem'
        response_key: 'solution'
      rollout_args:
        temperature: 1.0
        top_p: 1.0
        logprobs: 0
    eval_tasksets:
      - name: math
        storage_type: file
        path: ${oc.env:TRINITY_TASKSET_PATH}
        split: 'test'
        format:
          prompt_key: 'problem'
          response_key: 'solution'
        rollout_args:
          temperature: 0.1
          top_p: 0.95
    default_workflow_type: math_boxed_workflow
    default_reward_fn_type: math_boxed_reward
  trainer_input:
    experience_buffer:
      name: math_buffer
      storage_type: queue
      # path: 'sqlite:///math.db'
explorer:
  eval_interval: 250
  runner_per_model: 8
  rollout_model:
    engine_num: 4
    tensor_parallel_size: 1  # Each engine uses 1 GPU
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    max_prompt_tokens: 1024
    max_response_tokens: 2048
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 250
  sync_timeout: 3600  # Increased from 2000 to 3600 seconds (1 hour)
trainer:
  save_interval: 100
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: true
      actor:
        use_dynamic_bsz: true
        ppo_max_token_len_per_gpu: 16384
        ulysses_sequence_parallel_size: 1
        optim:
          lr: 6e-8
      ref:
        log_prob_use_dynamic_bsz: ${trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}
        log_prob_max_token_len_per_gpu: ${trainer.trainer_config.actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
        ulysses_sequence_parallel_size: ${trainer.trainer_config.actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size
