project: "Trinity-RFT-gsm8k-test-opmd"
name: "opmd_test"
checkpoint_root_dir: /PATH/TO/CHECKPOINT/
algorithm:
  algorithm_type: opmd
  repeat_times: 8
model:
  model_path: /PATH/TO/MODEL/
  max_prompt_tokens: 512
  max_response_tokens: 512
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 96
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: gsm8k
      storage_type: file
      path: '{path to datasets}/gsm8k/main' # the path where your jsonl or parquet files are located; use {path to datasets}/gsm8k/socratic for Socratic dataset
      format:
        prompt_key: 'question'
        response_key: 'answer'
      rollout_args:
        temperature: 1.0
        logprobs: 0
    default_workflow_type: 'math_workflow'
  trainer_input:
    experience_buffer:
      name: gsm8k_buffer
      storage_type: queue
      path: 'sqlite:///gsm8k_opmd.db'
explorer:
  runner_num: 32
  rollout_model:
    engine_type: vllm_async
    engine_num: 2
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 10
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/opmd_gsm8k/train_opmd_gsm8k.yaml'
  save_interval: 100
