project: "Trinity-RFT-toolace"
name: "qwen2.5-7B-toolace"
checkpoint_root_dir: /PATH/TO/CHECKPOINT/
algorithm:
  algorithm_type: grpo
  repeat_times: 8

model:
  model_path: /PATH/TO/MODEL/
  max_prompt_tokens: 4096
  max_response_tokens: 8192
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 128
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: toolace_data
      storage_type: file
      path: examples/grpo_toolcall/toolace_data
      # format: []
      rollout_args:
        n: 8
        temperature: 1.0
        logprobs: 0
    eval_tasksets: []
    default_workflow_type: 'toolcall_workflow'
  trainer_input:
    experience_buffer:
      name: toolace_buffer
      storage_type: queue
      path: 'sqlite:///toolace.db'
explorer:
  eval_interval: 50
  runner_num: 32
  rollout_model:
    engine_type: vllm_async
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 1
  sync_timeout: 3600
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/grpo_toolcall/train_toolace.yaml'
  save_interval: 100
