project: "dpo_example"
name: "trinity_dpo"
mode: train
algorithm:
  algorithm_type: dpo
  kl_loss_fn: k1
  kl_loss_fn_args:
    kl_coef: 0.1
checkpoint_root_dir: /PATH/TO/CHECKPOINT/
model:
  model_path: /PATH/TO/MODEL
  max_response_tokens: 1024
  max_model_len: 1536
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 2
  train_batch_size: 64
  trainer_input:
    experience_buffer:
      name: dpo_buffer
      storage_type: file
      enable_progress_bar: True
      path: /PATH/TO/DATASET/
      format:
        prompt_type: plaintext # plaintext/messages
        prompt_key: prompt
        chosen_key: chosen
        rejected_key: rejected
synchronizer:
  sync_method: 'checkpoint'
  sync_interval: 30
  sync_timeout: 1200
trainer:
  save_interval: 30
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: false
      actor:
        use_dynamic_bsz: false
        ppo_micro_batch_size_per_gpu: 2
        ppo_max_token_len_per_gpu: 16384
        ulysses_sequence_parallel_size: 1
        optim:
          lr: 5e-7
          lr_warmup_steps_ratio: 0.03  # the total steps will be injected during runtime
          min_lr_ratio: 0.1   # only useful for warmup with cosine
          warmup_style: cosine  # select from constant/cosine
          total_training_steps: 200
          betas: [0.9, 0.95]
      ref:
        log_prob_micro_batch_size_per_gpu: 2
        log_prob_use_dynamic_bsz: ${trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}
        log_prob_max_token_len_per_gpu: ${trainer.trainer_config.actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
        ulysses_sequence_parallel_size: ${trainer.trainer_config.actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size
    trainer:
      balance_batch: false
