from abc import ABC, abstractmethod
from typing import Dict, Tuple

import torch

from trinity.algorithm.utils import masked_mean
from trinity.utils.registry import Registry

ENTROPY_LOSS_FN = Registry("entropy_loss_fn")


class EntropyLossFn(ABC):
    """
    Entropy loss function.
    """

    @abstractmethod
    def __call__(
        self,
        entropy: torch.Tensor,
        action_mask: torch.Tensor,
        **kwargs,
    ) -> Tuple[torch.Tensor, Dict]:
        """
        Args:
            entropy (`torch.Tensor`): The entropy generated by the policy model.
            action_mask (`torch.Tensor`): The action mask.

        Returns:
            `torch.Tensor`: The calculated entropy loss.
            `Dict`: The metrics for logging
        """

    @classmethod
    @abstractmethod
    def default_args(cls) -> Dict:
        """
        Returns:
            `Dict`: The default arguments for the entropy loss function.
        """


@ENTROPY_LOSS_FN.register_module("basic")
class BasicEntropyLossFn(EntropyLossFn):
    """
    Basic entropy loss function.
    """

    def __init__(self, entropy_coef: float):
        self.entropy_coef = entropy_coef

    def __call__(
        self,
        entropy: torch.Tensor,
        action_mask: torch.Tensor,
        **kwargs,
    ) -> Tuple[torch.Tensor, Dict]:
        entropy_loss = masked_mean(entropy, action_mask)
        return entropy_loss * self.entropy_coef, {"entropy_loss": entropy_loss.detach().item()}

    @classmethod
    def default_args(cls) -> Dict:
        return {"entropy_coef": 0.0}
