project: opmd_math
name: opmd_math_example
checkpoint_root_dir: 'experiments/'
model:
  model_path: '{your_path}/Qwen2.5-3B-Instruct' # the path to your model, 
algorithm:
  algorithm_type: opmd
  repeat_times: 8
cluster:
  node_num: 2
  gpu_per_node: 8
buffer:
  total_epochs: 10
  batch_size: 120
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: math
      storage_type: file
      path: '{your_path}/MATH/data'
      format:
        prompt_key: 'problem'
        response_key: 'solution'
      rollout_args:
        temperature: 1.0
        logprobs: 0
    eval_tasksets:
      - name: math
        storage_type: file
        path: '{your_path}/MATH/data'
        split: 'test'
        format:
          prompt_key: 'problem'
          response_key: 'solution'
    default_workflow_type: math_boxed_workflow
    default_reward_fn_type: math_boxed_reward
    # default_reward_fn_type: 'rm_gallery_reward'

  trainer_input:
    experience_buffer:
      name: math_buffer
      storage_type: queue
      path: 'sqlite:///math.db'
explorer:
  eval_interval: 125
  runner_num: 128
  rollout_model:
    engine_type: vllm_async
    engine_num: 8
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    max_prompt_tokens: 1024
    max_response_tokens: 2048
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 250
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/opmd_math/train_math.yaml'
  save_interval: 100
